#!/bin/bash
# Author: lukasjoc
# Desc: Handles initialization of all scripts
set -u

readonly $envm_scripts_dir="$envm"/scripts

for script in "$envm_scripts_dir/*"; do
	source "$script"
done

if [ -z "${envm_wdir+x}" ]; then
  echo "could not find envm_wdir environment variable"
	echo "Please set envm_wdir variable like this echo 'export envm_wdir='~/some/dir'' >> ~/.bashrc "
fi

if [ ! -z "${envm_wdir+x}" ]; then
	if [ ! -d "$envm_wdir" ]; then
  	echo "could not find working directory as requested in envm_wdir"
	fi
fi

# Message ------------------------------------------------
figlet "Hello, $USER"
neofetch || uname -a
fortune || true
# ------------------------------------------------

# automatic update looking for the value in ./cache/start_epoch.dat
if [[ $envm_auto_update_days -le 1 ]]; then
	if [ ! -n "${envm+x}" ]; then
		dat_file="$HOME/.cache/envm/start_epoch.dat"

		if [ ! -d "$HOME/.cache/envm" ]; then
			mkdir -p "$HOME/.cache/envm"
		fi

  	if [ ! -f "$dat_file" ]; then
   		date +%s > $dat_file
  	fi

  	declare -i update_epoch=$(( 60 * 60 * 24 * $envm_auto_update_days + $(cat $dat_file) ))
  	if [[ "$(date +%s)" -ge $update_epoch ]]; then
    	date +%s > "$dat_file"
			envmupdate
  	fi
	else
		echo "could not find envm source directory"
	fi
fi

