#!/bin/bash
# Author: lukasjoc
# Desc: Handles uninstalling envm manager from all places
set -u

while true; do
  read -rp "Are you sure you want to say goodbye to env M anager? [N/y]" input
  case $input in 
  [yY][eE][sS]|[yY]*)
    rm -rf $envm
    rm  -rf /usr/local/bin/envm
    echo "Deleted env Manager successfully..."
    break;;
  [nN][oO]|[nN]*)
    echo "Exiting..."
    exit;;
  *)
    echo "Exiting..."
    exit;;
  esac
done

