#!/bin/sh

cat << "EOM"
Script for homebrew updating script brewautoupdate.sh
lukasjoc, 2019
https://lukasjoc.com
Updates Homebrew and brew caskroom
===================================================
EOM

#update is updating the local homebrew-core repository
#and upgrading brews if possible, updating and upgrading casks 
#if possible, cleaning the brew installation if possible
function update {
  echo "Updating and Upgrading Homebrew/Core"
	cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
	git reset --hard origin/master
	brew upgradel
	echo "Upgrading casks if any..."
	brew cask upgrade
	echo "Cleaning up..."
	brew cleanup
}

update
