#!/bin/bash


gobuild() {
	if [[ $# -lt 0 || $# -gt 1 || $1 == "" ]]; then
		echo "Usage: gobuild <target_executable_name>"
		return
	fi

	os=$(go env GOOS)
	arch=$(go env GOARCH)
	binary_name="${1%.*}"
	
	echo "Building $binary_name for $arch on $os"
	GOOS=$os GOARCH=$arch go build -a -ldflags="-s -w" -o $binary_name
}

