#!/bin/bash

# Check for system
if [[ $(uname -s) == "Darwin" ]]; then
  alias ls="ls -FG"
  alias watchdir="watch -d ls -halFG"
  alias bc="brew cask"
	
else

  alias ls="ls -F --color=auto"
  alias watchdir="watch -d ls -halF --color=auto"

fi

alias ll="ls -hal"
alias ..="cd ../"
alias ...="cd ../../"
alias datef="date +'%d.%m.%y'"
alias python="python3"
alias pip="pip3"
alias mkdir="mkdir -p"
alias vi="mvim -v"
alias vim="mvim -v"
alias rm="rm -r"
alias dc="docker-compose"
alias sqlite="sqlite3"
alias type="type -a"
alias cl="clear"

count() {
	ls | wc -l
}

ns() {
	exec $SHELL -l
}

pgit() {
	git branch --merged master --no-color | grep -v master | grep -v stable | xargs git branch -d
}

npmls() {
	npm list -g --depth=0
}

fun() {
	cd $envm_wdir
}

activate_env() {
	$PWD venv/bin/activate
}

gobench() {
	go test -v --bench . --benchmem
}

goclean() {
	go clean -x -r -cache -modcache
}

speedtest() {
	curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -
}

