#!/bin/bash
# Author: lukasjoc
# Desc: Provokes and defines some aliases and functions
set -u

# Check for system
if [[ "$(uname -s)" == "Darwin" ]]; then
  alias ls="ls -FG"
  alias watchdir="watch -d ls -halFG"
  alias	bc="brew cask"
	alias updatedb="sudo /usr/libexec/locate.updatedb"
	alias vi="mvim -v"
	alias vim="mvim -v"
else
  alias ls="ls -F --color=auto"
  alias watchdir="watch -d ls -halF --color=auto"
fi

alias ll="ls -hal"
alias ..="cd ../"
alias ...="cd ../../"
alias datef="date +'%d.%m.%y'"
alias python="python3"
alias pip="pip3"
alias rm="rm -ir"
alias cp="cp -i"
alias mv="mv -i"
alias dc="docker-compose"
alias type="type -a"
alias cl="clear"
alias cal="ncal"

doom() {
	if ! command -v emacs >/dev/null 2>&1; then
		return 0
	fi
	"$HOME/.emacs.d/bin/doom" "$@"
}

# reload $SHELL with -
ns() {
	exec "$SHELL" -l
}

# prune git branches
pgit() {
	git branch --merged main --no-color | grep -v main | grep -v stable | xargs git branch -d
}

# ls all global installed npm packages
npmls() {
	npm list -g --depth=0
}

# quick alias to cd into working dir
fun() {
	cd "$ENVM_WDIR" || return
}

# quick alias to cd into working dir
fn() {
	cd "$ENVM_WDIR" || return
}

# activate your venv when in $PWD
activate_env() {
	"$PWD" venv/bin/activate
}

# test and benchmark go code
gobench() {
	go test -v --bench . --benchmem -race
}

# clean modcache and cache for golang mod paths
goclean() {
	go clean -x -r -cache -modcache
}

# run a simple and clean speedtest with python
speedtest() {
	curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/main/speedtest.py | python -
}

# Taken from https://github.com/jessfraz/dotfiles/blob/main/.functions
# Thank you github.com/jessfraz
# Get colors in manual pages
man() {
	env \
		LESS_TERMCAP_mb="$(printf '\e[1;31m')" \
		LESS_TERMCAP_md="$(printf '\e[1;31m')" \
		LESS_TERMCAP_me="$(printf '\e[0m')" \
		LESS_TERMCAP_se="$(printf '\e[0m')" \
		LESS_TERMCAP_so="$(printf '\e[1;44;33m')" \
		LESS_TERMCAP_ue="$(printf '\e[0m')" \
		LESS_TERMCAP_us="$(printf '\e[1;32m')" \
		man "$@"
}

# cd to goals repository
goals() {
	cd "$HOME/owncloud/goals" || return
}

