#!/usr/local/bin/bash

alias ..="cd ../"
alias ...="cd ../../"
alias ....="cd ../../../"
alias dc="docker-compose"
alias kctl="kubectl"
alias mkube="minikube"
alias pb="perlbrew"
alias pbl="perlbrew list"
alias br="brew"
alias bc="brew cask"
alias ls="ls -GF"
alias ll="ls -alF"
alias mkdir="mkdir -p"
alias rmdir="rm -rf"
alias count="ls -l | grep "" -c"
alias watchdir="watch -d ls -halFG "
alias cat="ccat"
alias mr="mysql -uroot -p"
alias newshell="exec $SHELL -l"
alias fun="cd $ENVM_WDIR/w/fun"
alias npmls="npm list -g --depth=0"
alias nimr="nim compile --run $1"
alias nimb="nim compile $1"
