#!/bin/bash
# Author: lukasjoc
# Desc: Defines build wappers for some often used build commands
set -u

# savely build a golang programm more efficient
gobuild() {
	local os arch binary_name

	os=$(go env GOOS)
	arch=$(go env GOARCH)
	binary_name="${1%.*}"
	
	echo -e "INFO: Building \e[37m$binary_name\e[0m for $arch on $os"
	GOOS="$os" GOARCH="$arch" go build \
		-a \
		-ldflags="-s -w" \
		-race \
		-o "$binary_name"

}

# build your tex files to pdfs  into a more standardized out/ dir so its a bit clearer
pdfbuild() {
	local out_dir out_format

	out_dir="$PWD/out"
	if [[ ! -d "$out_dir" ]]; then
		mkdir -p "$out_dir"
	fi

	pdflatex \
		-output-directory="$out_dir" \
		-output-format="$out_format" \
		-8bit "$@"

}
