#!/bin/bash
# Author: lukasjoc
# Desc: Defines build wappers for some often used build commands
set -u

# savely build a golang programm more efficient
gobuild() {
	local os arch binary_name

	os=$(go env GOOS)
	arch=$(go env GOARCH)
	binary_name="${1%.*}"
	
	echo -e "INFO: Building \e[37m$binary_name\e[0m for $arch on $os"
	GOOS="$os" GOARCH="$arch" go build \
		-a \
		-ldflags="-s -w" \
		-race \
		-o "$binary_name"

}


pdflatexbuild() {
	if [[ $# -ge 1 ]]; then
		pdflatex \
			-output-directory=out \
			"$1"
	fi
}
