#!/bin/bash
# Defines just some essential functions.. Functions that are not used at least twice per week are being removed
set -u

# list docker info neatly and with color
cooldocker() {

	local ic nc vc cc

	cc=$(docker container ls -q | wc -l | sed 's/ //g')
	ic=$(docker images -q | wc -l | sed 's/ //g' )
	nc=$(docker network ls -f dangling=true -q | wc -l | sed 's/ //g')
	vc=$(docker volume ls -q | wc -l | sed 's/ //g')
	
	echo -e "\n[ \e[36m$cc\e[0m ] | CONTAINERS:"
	docker container ls | while read -r line; do
		if echo "$line" | grep -q "CONTAINER ID"; then
			echo -e "$line\t\tIP ADDRESS"
		else
			
			cid=$(echo "$line" | awk '{print $1}');
			cip=$(docker inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}" "$cid");
			echo -e "${line}\t${cip}"
		fi
	done; echo

	echo -e "[ \e[36m$ic\e[0m ] | IMAGES:"
	docker images -f dangling=false; echo
	
	echo -e "[ \e[36m$nc\e[0m ] | NETS:"
	docker network ls -f dangling=true; echo
	if [ "$vc" -ge 1 ]; then
		echo -e "[ \e[36m$vc\e[0m ] | VOLUMES:"
		docker volume ls; echo
	fi

}

# remove all containers, images, volumes, networks
# HEFTY thing to do BE SURE TO DO it. YOLO
alias killdocker="docker system prune -a"
