#!/bin/sh

cat << "EOF"
  __ _       _     _      _            _ 
 / _(_) __ _| |__ | |_ __| | ___   ___| | _____ _ __
| |_| |/ _` | '_ \| __/ _` |/ _ \ / __| |/ / _ \ '__|
|  _| | (_| | | | | || (_| | (_) | (__|   <  __/ |
|_| |_|\__, |_| |_|\__\__,_|\___/ \___|_|\_\___|_|
       |___/
EOF

cat << EOF
lukasjoc, 2019
https://lukasjoc.com
I mean there is a utility in the 
docker CLI which does the same
but this is way cooler, isn't it
===================================================
EOF

function fight {
       echo "Fighting networks and docker junk.."
       docker system prune
}

echo "I'm gonna go to battle for you. I'll triumph or die in honor."
# TODO: ASK user to set the script into the /usr/local/bin path to access it globally

fight

printf 🐋=IMAGES\ CURRENTLY\ USED\ =🐋:" "; docker images | grep "" -c && printf "\n";
printf 🐋=CONTAINERS\ CURRENTLY\ RUNNING\ =🐋:" "; docker container ls | grep "" -c && printf "\n";
printf 🐋=NETWORKS\ CURRENTY\ USED\ =🐋:" "; docker network ls | grep "" -c && printf "\n";
echo "\nI did it sir $USER. I won with honor"



