#!/bin/bash

gobuild() {
	if [ ! command -v go >/dev/null 2>&1 ] || [ -z "$GOPATH" ]; then
  	echo "Error: golang is not installed or GOPATH is not set or added to PATH"
  	echo "What is the GOPATH? => https://github.com/golang/go/wiki/GOPATH"
  	echo "How to set GOPATH? => https://github.com/golang/go/wiki/SettingGOPATH"
		return
	fi

	if ! echo "$PATH" | grep -q "$GOPATH"; then
  	echo "Error: golang is not installed or GOPATH is not set or added to PATH"
  	echo "What is the GOPATH? => https://github.com/golang/go/wiki/GOPATH"
  	echo "How to set GOPATH? => https://github.com/golang/go/wiki/SettingGOPATH"
  	return
	fi

	if [[ $# -lt 0 || $# -gt 1 || $1 == "" ]]; then
		echo "Usage: gobuild <target_executable_name>"
		return
	fi

	os=$(go env GOOS)
	arch=$(go env GOARCH)
	binary_name="${1%.*}"
	
	echo "Building $binary_name for $arch on $os"
	GOOS=$os GOARCH=$arch go build -a -ldflags="-s -w" -o $binary_name
}
