#!/bin/bash

gobuild() {
	if [ ! command -v go >/dev/null 2>&1 ] || [ -z "$GOPATH" ]; then
  	echo "Error: golang is not installed or GOPATH is not set or added to PATH"
  	echo "What is the GOPATH? => https://github.com/golang/go/wiki/GOPATH"
  	echo "How to set GOPATH? => https://github.com/golang/go/wiki/SettingGOPATH"
		return
	fi

	if ! echo "$PATH" | grep -q "$GOPATH"; then
  	echo "Error: golang is not installed or GOPATH is not set or added to PATH"
  	echo "What is the GOPATH? => https://github.com/golang/go/wiki/GOPATH"
  	echo "How to set GOPATH? => https://github.com/golang/go/wiki/SettingGOPATH"
  	return
	fi

	if [[ $# -lt 0 || $# -gt 1 || $1 == "" ]]; then
		echo "Usage: gobuild <target_executable_name>"
		return
	fi

	GOOS=$(go env GOOS)
	GOARCH=$(go env GOARCH)
	echo "Building $1 for $GOARCH on $GOOS"
 	GOOS=$GOOS GOARCH=$GOARCH go build -a -ldflags="-s -w" -o $1
}
