#!/bin/bash
# Author: lukasjoc
# Desc: Scripts for mac, JUST for mac
set -u

if [[ "$(uname -s)" == "Darwin" ]]; then

	# update brew packages, and casks,
	# clean package system and do a doctor
	runbrewstuff() {
		echo "Running brew update..."
		brew update
		brew upgrade

		echo "Running brew upgrade..."
		brew cask upgrade --greedy

		echo "Running brew cleanup..."
		rm -rf "$(brew --cache)"

		echo "Cleaning up system..."
		brew cleanup
		brew doctor

		echo "Done ;)"
	}

	# alias the open command to the finder
	# alias to be more connected to the apple system
	finder() {
		open "$@"
	}

	# System RAM Stats and stuff.
	free() {
		local path_to_exec="$ENVM/bin/free"
		base64 -D "$path_to_exec" | python3
	}

fi
