#!/bin/bash
# Author: lukasjoc
# Desc: Sets up my nice shell prompt with git functionality

# get current branch in git repo
parse_git_branch() {
	local bra=`git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'`
	if [ ! "${bra}" == "" ]; then
		local sta=`parse_git_dirty`
		echo "(${bra}${sta}) "
	else
		echo ""
	fi
}

# get current status of git repo
parse_git_dirty() {
	local status=`git status 2>&1 | tee`
	local modified=`echo -n "${status}" 2> /dev/null | grep "modified:" &> /dev/null; echo "$?"`
	local bits=''
	
	if [ "${modified}" == "0" ]; then
		bits="*${bits}"
	fi
	
	if [ ! "${bits}" == "" ]; then
		echo " ${bits}"
	else
		echo ""
	fi
}

case "$TERM" in
  xterm-color|*-256color) color_prompt=yes;;
esac


# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Setup promt like this: (user)::(hostname) (PWD)$ ((branch) (status))
export PS1="\[\e[1;32m\]\u\[\e[m\]::\[\e[1;31m\]\h\[\e[m\] \[\e[1;10m\]\W\[\e[m\]\\$ \[\e[1;36m\]\`parse_git_branch\`\[\e[m\]"
