#!/bin/bash
# Author: lukasjoc
# License: MIT
# Desc: today the really simple todo command using $EDITOR for writing and a git repo for hosting all things
#######
set -u

today() {
	local todo_name todo_repository todo_collection current_todo

	todo_name="$(date +'%d.%m.%y').md"
	todo_repository="$HOME/.local/share/todo" # Following XDG path conventions
	todo_collection="$(date +'%m')_$(date +'%y')"
	current_todo="$todo_repository/$todo_collection/$todo_name"

	__usage() {
		printf '\n%s\n\n' "Manage todos without overhead and within the workflow"
		printf '%s\n\n' "USAGE:"
		printf '%s\n\n'  " today [ -h ] [ -n <-1...> ] [ new (With: $EDITOR) ]
		[ update (With: $EDITOR) ]
		[ save ] [ sync ] [ list ]"
	}
	
	__change() {
		# Create month dir if not present
		if [[ ! -d "$todo_repository/$todo_collection" ]]; then
			mkdir -p "$todo_repository/$todo_collection"
		fi

		"$EDITOR" "$current_todo"
		return 0
	}

	__save() {
		cd "$todo_repository" || exit
		git add "$current_todo" && git commit -m "add current todo $todo_name"
		git push
		cd - || exit
		return 0
	}

	__sync() {
		cd "$todo_repository" || exit
		git checkout main
		git pull --rebase --stat origin main
		cd "$OLDPWD" || exit

		return 0
	}

	__list() {
		ls -R "$todo_repository"
		return 0
	}
	
	__list_gone() {
		local file day
		day=$( ($(date '+%d') "$1" ) )
		if [[ "$day" -le 9 ]]; then
			day="0$day"
		fi

		file=$day.$(date +'%m.%y').md
		chroma "$todo_repository/$todo_collection/$file"
	}

	# list current todolist for the current day
	# using less or chroma to have colored
	if [[ "$#" == "0" ]]; then
		chroma "$current_todo"
		return 0
	fi

	## handle single flags upper and lowercase
	local opt
	local OPTARG
	local OPTIND
	while getopts ":hn:" opt; do
		case ${opt} in
			h) __usage;;
			n) __list_gone "$OPTARG";;
			\?) echo "Invalid Option: -$OPTARG" 1>&2;  return 1;;
			:) echo "Required Data: -$OPTARG" 1>&2;  return 1;;
		esac
	done
	
	local cmd
	cmd="${1:-}"; shift
	case "$cmd" in
		new) __change;;
		update) __change;;
		save) __save;;
		sync) __sync;;
		list) __list;;
	esac

	shift $((OPTIND -1))
}
