#!/bin/bash
# Manage your XDG_* path. Show contents & delete stuff from it
#######
set -u

xdgm() {

	__usage() {
		printf '\n%s\n\n' "Manage your XDG PATH. Show contents & delete stuff from it"
		printf '%s\n\n'  " xdgm [ -h ] [ rm -n <name> ]"
	}

	local status_color="\e[1;32m"
	local -a XDG_PATHS=(
		"$HOME/.config"
		"$HOME/.local/share"
		"$HOME/.cache"
	)

	__rm() {
	
		if [[ "$#" == 0 ]]; then
			__usage
			return 1
		fi

		for p in "${XDG_PATHS[@]}"; do
			local candidate="${p:?}/$*"

			if [[ -d "$candidate" ]]; then
				echo "Found candidate for $* in $p Pruning..."
				rm -rf "$candidate"
				echo "removing $candidate"
			else
				echo -e "Found $status_color 0 \e[0m candidates for $* in $p Skipping..."
			fi

		done
	}

	# list XDG PATH
	if [[ "$#" == "0" ]]; then
		local total_apps total_size
		for p in "${XDG_PATHS[@]}"; do
			total_apps="$(ls "$p" | wc -l | sed 's/ //g' )"
			total_size="$(du -sh "$p" | awk '{print $1}')"
			echo -e "==> $status_color$p  [ AppsCount: $total_apps \ DiskSpace: $total_size ]   \e[0m"
			ls -F "$p" && echo
		done
	fi


	local opt OPTARG OPTIND
	
	# handle global flags
	while getopts ":h" opt; do
		case ${opt} in
			h) __usage;;
			\?) echo "Invalid Option: -$OPTARG" 1>&2;  return 1;;
		esac
	done

	# handle global subcommands
	local cmd
	cmd="${1:-}"; shift
	case "$cmd" in
		rm) __rm "$@";;
	esac

	shift $((OPTIND -1))
}
