#!/bin/bash
# Manage your XDG_* path. Show contents & delete stuff from it
#######
set -u

xdgm() {

# print usage information
__usage() {
	cat <<EOF
Manage your XDG PATH. Show contents & delete stuff from it.

Usage:
 xdgm [flags]
 xdgm [command]

Commands:
 rm     remove candidate
 help   print the help message

Flags:
 -h, --help   print the help message

Use "xdgm [help] | [-h|--help]" for more information about this script.
EOF
}

local status_color="\e[1;32m"
local -a XDG_PATHS=(
	"$HOME/.config"
	"$HOME/.local/share"
	"$HOME/.local/bin"
	"$HOME/.cache"
)


remove() {

if [[ "$#" == 0 ]]; then __usage; return 1; fi

for p in "${XDG_PATHS[@]}"; do
	local candidate="${p:?}/$*"
	if [[ -d "$candidate" ]]; then
		echo "Found candidate for $* in $p Pruning..."
		rm -rf "$candidate"
		echo "removing $candidate"
	else
		echo -e "Found $status_color 0 \e[0m candidates for $* in $p Skipping..."
	fi
done
}

#  list XDG PATH
if [[ "$#" -eq 0 ]]; then
	local total_apps total_size
	for p in "${XDG_PATHS[@]}"; do
		total_apps="$(ls "$p" | wc -l | sed 's/ //g' )"
		total_size="$(du -sh "$p" | awk '{print $1}')"
		echo -e "==> $status_color$p  [ AppsCount: $total_apps \ DiskSpace: $total_size ]   \e[0m"
		ls -F "$p" && echo
	done
fi

# unprocessed_args=()
while [[ "$#" -ne 0 ]]; do
	case "$1" in
		rm) remove "$2"; return 0;;
		-h|--help|help) __usage; return 0;; # print help
		*) __usage; return 1;; # print usage if command, flag not processable
	esac
	shift
done

}
